name: webapp-adminserein

services:
  postgres:
    image: postgres
    container_name: webapp-adminserein-postgres
    environment:
      POSTGRES_DB: webapp-adminserein
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - webapp-adminserein_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  webapp-adminserein_postgres_data:
